M48
; DRILL file {KiCad 9.0.3} date 2025-07-21T12:14:54+1000
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-07-21T12:14:54+10:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.3
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.850
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X142.885Y-66.02
X147.735Y-66.02
T2
X142.585Y-62.99
X148.035Y-62.99
M30
